import { type DefaultTheme } from 'vitepress'

export function JsSidebar(): DefaultTheme.SidebarItem[] {
	return [
		{
			text: 'JS进阶',
			link: 'index',
			items: [
				{ text: '首页', link: 'index' },
				{
					text: 'js基础',
					collapsed: true,
					base: 'js/基础/',
					items: [
						{ text: 'index', link: 'index' },
						{ text: 'Dom节点', link: 'Dom节点' },
						{ text: '字符串常用的方法', link: '字符串常用的方法' },
						{ text: '数组常用方法', link: '数组常用方法' },
						{ text: '数组字符串其他方法', link: '数组字符串其他方法' },
						{ text: '类数组', link: '类数组' },
						{ text: 'Math常用的方法', link: 'Math常用的方法' },
						{ text: '浅拷贝与深拷贝', link: '浅拷贝与深拷贝' },
						{ text: '类型转换', link: '类型转换' },
						{ text: '递归', link: '递归' },
						{ text: '函数记忆', link: '函数记忆' },
						{ text: '防抖节流', link: '防抖节流' },
						{ text: '重绘和回流', link: '重绘和回流' },
					],
				},
				{
					text: 'js算法',
					collapsed: true,
					base: 'js/算法/',
					items: [
						{ text: 'index', link: 'index' },
						{ text: '冒泡排序', link: '冒泡排序' },
						{ text: '选择排序', link: '选择排序' },
						{ text: '插入排序', link: '插入排序' },
						{ text: '归并排序', link: '归并排序' },
						{ text: '计数排序', link: '计数排序' },
						{ text: '基数排序', link: '基数排序' },
					],
				},
				{
					text: 'js进阶',
					collapsed: true,
					base: 'js/进阶/',
					items: [
						{ text: 'index', link: 'index' },
						{ text: '运算符进阶', link: '运算符进阶' },
						{ text: 'js风格指南', link: 'js风格指南' },
						{ text: 'js测试题自测', link: 'js测试题自测' },
						{ text: '油猴脚本', link: '油猴脚本' },
					],
				},
				{
					text: 'js组件',
					collapsed: false,
					base: 'js/组件/',
					items: [
						{ text: 'highLight代码高亮组件', link: 'highLight代码高亮组件' },
						{ text: 'sse（对话）', link: 'fetchEventSource' },
					],
				},
				{
					text: 'js深入',
					collapsed: false,
					base: 'js/深入/',
					items: [
						{ text: '01_深入JavaScript运行原理', link: '01_深入JavaScript运行原理' },
						{ text: '02_JS内存管理和闭包', link: '02_JS内存管理和闭包' },
						{ text: '03_JS内存管理和闭包-day03', link: '03_JS内存管理和闭包-day03' },
						{ text: '04_JS函数的this指向', link: '04_JS函数的this指向' },
						{ text: '05_JS函数的this指向', link: '05_JS函数的this指向' },
						{ text: '06_JS函数增强知识点补充', link: '06_JS函数增强知识点补充' },
						{ text: '07_JS额外知识补充', link: '07_JS额外知识补充' },
						{ text: '08_深入JS面向对象', link: '08_深入JS面向对象' },
						{ text: '09_深入JS面向对象二', link: '09_深入JS面向对象二' },
						{ text: '10_深入JS面向对象继承', link: '10_深入JS面向对象继承' },
						{ text: '11_深入JS面向对象继承', link: '11_深入JS面向对象继承' },
						{ text: '12_JS面向对象补充', link: '12_JS面向对象补充' },
						{ text: '13_ES6~ES12-一', link: '13_ES6~ES12-一' },
						{ text: '14_ES6~ES12-二', link: '14_ES6~ES12-二' },
						{ text: '15_ES6~ES12-三', link: '15_ES6~ES12-三' },
						{ text: '16_ES6~ES12-四', link: '16_ES6~ES12-四' },
						{ text: '17_Proxy-Reflect-响应式', link: '17_Proxy-Reflect-响应式' },
						{ text: '18_Promise使用详解', link: '18_Promise使用详解' },
						{ text: '19_Promise使用详解的副本', link: '19_Promise使用详解的副本' },
						{ text: '20_Iterator-Generator', link: '20_Iterator-Generator' },
						{ text: '21_await-async-事件循环', link: '21_await-async-事件循环' },
						{ text: '22_await-async-事件循环', link: '22_await-async-事件循环' },
						{ text: '23_异常处理_JavaScript模块化', link: '23_异常处理_JavaScript模块化' },
						{ text: '24_JavaScript模块化', link: '24_JavaScript模块化' },
						{ text: '25_npm包管理工具', link: '25_npm包管理工具' },
						{ text: '26_JSON-Storage', link: '26_JSON-Storage' },
						{ text: '27_DOM-BOM操作', link: '27_DOM-BOM操作' },
						{ text: '28_DOM-BOM操作', link: '28_DOM-BOM操作' },
						{ text: '29_手写防抖节流', link: '29_手写防抖节流' },
						{ text: '30_手写防抖节流-深拷贝-事件总线', link: '30_手写防抖节流-深拷贝-事件总线' },
					],
				},
			],
		},
	]
}
